Ag:
  Event:
    eventHandlers:
      sync:
        'Ag\Event\EventHandler\StubEventHandler': 'Ag\Event\EventHandler\StubEventHandler'

TYPO3:
  Flow:
    persistence:
      doctrine:
        eventListeners:
          -
            events: ['postFlush']
            listener: 'Ag\Event\Service\EventService'